export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const postConstant = {
  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  GET_POST_REQUEST: "GET_POST_REQUEST",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  GET_POST_FAILURE: "GET_POST_FAILURE",

  GET_USER_POST_REQUEST: "GET_USER_POST_REQUEST",
  GET_USER_POST_SUCCESS: "GET_USER_POST_SUCCESS",
  GET_USER_POST_FAILURE: "GET_USER_POST_FAILURE",

  GET_REFRESH_USER_POST_REQUEST: "GET_REFRESH_USER_POST_REQUEST",
  GET_REFRESH_USER_POST_SUCCESS: "GET_REFRESH_USER_POST_SUCCESS",
  GET_REFRESH_USER_POST_FAILURE: "GET_REFRESH_USER_POST_FAILURE",

  GET_REFRESH_POST_REQUEST: "GET_REFRESH_POST_REQUEST",
  GET_REFRESH_POST_SUCCESS: "GET_REFRESH_POST_SUCCESS",
  GET_REFRESH_POST_FAILURE: "GET_REFRESH_POST_FAILURE",
};
